library WoWReforgedMapComputerStartLocations initializer Init requires WoWReforgedComputerStartLocations, WoWReforgedRaces

// Has to match StartLocationsPopup.
private function Init takes nothing returns nothing
	// Kalimdor
	call AddComputerStartLocationRectWithShipyard(gg_rct_Town_Hall_Teldrassil, gg_rct_Town_Hall_Shipyard_Teldrassil)
	call AddComputerStartLocationPossibleRaceLast(WOWR_RACE_NIGHT_ELF)
	call AddComputerStartLocationPossibleRaceLast(WOWR_RACE_FURBOLG)
	call AddComputerStartLocationPossibleRaceLast(WOWR_RACE_SATYR)

	call AddComputerStartLocationRectNoShipyard(gg_rct_Town_Hall_Hyjal)
	call AddComputerStartLocationPossibleRaceLast(WOWR_RACE_NIGHT_ELF)
	call AddComputerStartLocationPossibleRaceLast(WOWR_RACE_FURBOLG)
	call AddComputerStartLocationPossibleRaceLast(WOWR_RACE_SATYR)

	call AddComputerStartLocationRectWithShipyard(gg_rct_Town_Hall_Orgrimmar, gg_rct_Town_Hall_Shipyard_Orgrimmar)
	call AddComputerStartLocationPossibleRaceLast(WOWR_RACE_ORC)
	call AddComputerStartLocationPossibleRaceLast(udg_RaceQuillboar)
	call AddComputerStartLocationPossibleRaceLast(WOWR_RACE_CENTAUR)

	call AddComputerStartLocationRectWithShipyard(gg_rct_Town_Hall_Thunder_Bluff, gg_rct_Town_Hall_Shipyard_Thunder_Bluff)
	call AddComputerStartLocationPossibleRaceLast(WOWR_RACE_TAUREN)
	call AddComputerStartLocationPossibleRaceLast(udg_RaceQuillboar)
	call AddComputerStartLocationPossibleRaceLast(WOWR_RACE_CENTAUR)

	call AddComputerStartLocationRectWithShipyard(gg_rct_Town_Hall_Echo_Isles, gg_rct_Town_Hall_Shipyard_Echo_Isles)
	call AddComputerStartLocationPossibleRaceLast(WOWR_RACE_TROLL)

	call AddComputerStartLocationRectWithShipyard(gg_rct_Town_Hall_Darkspear_Islands, gg_rct_Town_Hall_Shipyard_Darkspear_Islands)
	call AddComputerStartLocationPossibleRaceLast(WOWR_RACE_MURLOC)
	call AddComputerStartLocationPossibleRaceLast(WOWR_RACE_DUNGEON)
	call AddComputerStartLocationPossibleRaceLast(WOWR_RACE_DRAGONKIN)

	call AddComputerStartLocationRectWithShipyard(gg_rct_Town_Hall_Theramore, gg_rct_Town_Hall_Shipyard_Theramore)
	call AddComputerStartLocationPossibleRaceLast(WOWR_RACE_KUL_TIRAS)
	call AddComputerStartLocationPossibleRaceLast(WOWR_RACE_HUMAN)

	call AddComputerStartLocationRectWithShipyard(gg_rct_Town_Hall_Kezan, gg_rct_Town_Hall_Shipyard_Kezan)
	call AddComputerStartLocationPossibleRaceLast(WOWR_RACE_GOBLIN)

	// Eastern Kingdoms
	call AddComputerStartLocationRectWithShipyard(gg_rct_Town_Hall_Stormwind, gg_rct_Town_Hall_Shipyard_Stormwind)
	call AddComputerStartLocationPossibleRaceLast(WOWR_RACE_STORMWIND)
	call AddComputerStartLocationPossibleRaceLast(WOWR_RACE_HUMAN)
	call AddComputerStartLocationPossibleRaceLast(WOWR_RACE_LORDAERON)
	call AddComputerStartLocationPossibleRaceLast(WOWR_RACE_GNOLL)
	call AddComputerStartLocationPossibleRaceLast(WOWR_RACE_BANDIT)
	call AddComputerStartLocationPossibleRaceLast(WOWR_RACE_WORGEN)

	call AddComputerStartLocationRectWithShipyard(gg_rct_Town_Hall_Kul_Tiras, gg_rct_Town_Hall_Shipyard_Kul_Tiras)
	call AddComputerStartLocationPossibleRaceLast(WOWR_RACE_KUL_TIRAS)
	call AddComputerStartLocationPossibleRaceLast(WOWR_RACE_HUMAN)
	call AddComputerStartLocationPossibleRaceLast(WOWR_RACE_LORDAERON)

	call AddComputerStartLocationRectNoShipyard(gg_rct_Town_Hall_Undercity)
	call AddComputerStartLocationPossibleRaceLast(WOWR_RACE_UNDEAD)

	call AddComputerStartLocationRectWithShipyard(gg_rct_Town_Hall_Ironforge, gg_rct_Town_Hall_Shipyard_Ironforge)
	call AddComputerStartLocationPossibleRaceLast(WOWR_RACE_DWARF)
	call AddComputerStartLocationPossibleRaceLast(WOWR_RACE_GNOME)
	call AddComputerStartLocationPossibleRaceLast(WOWR_RACE_KOBOLD)

	call AddComputerStartLocationRectWithShipyard(gg_rct_Town_Hall_Sunwell_Grove, gg_rct_Town_Hall_Shipyard_Sunwell_Grove)
	call AddComputerStartLocationPossibleRaceLast(WOWR_RACE_HIGH_ELF)

	call AddComputerStartLocationRectWithShipyard(gg_rct_Town_Hall_Sunstrider_Isle, gg_rct_Town_Hall_Shipyard_Sunstrider_Isle)
	call AddComputerStartLocationPossibleRaceLast(WOWR_RACE_BLOOD_ELF)

	// Northrend
	call AddComputerStartLocationRectWithShipyard(gg_rct_Town_Hall_Northrend_West, gg_rct_Town_Hall_Shipyard_Northrend_West)
	call AddComputerStartLocationPossibleRaceLast(WOWR_RACE_UNDEAD)

	call AddComputerStartLocationRectWithShipyard(gg_rct_Town_Hall_Northrend_East, gg_rct_Town_Hall_Shipyard_Northrend_East)
	call AddComputerStartLocationPossibleRaceLast(WOWR_RACE_NERUBIAN)
	call AddComputerStartLocationPossibleRaceLast(WOWR_RACE_FACELESS_ONE)

	call AddComputerStartLocationRectWithShipyard(gg_rct_Town_Hall_Moaki_Harbor, gg_rct_Town_Hall_Shipyard_Moaki_Harbor)
	call AddComputerStartLocationPossibleRaceLast(WOWR_RACE_TUSKARR)
	call AddComputerStartLocationPossibleRaceLast(WOWR_RACE_VRYKUL)

	call AddComputerStartLocationRectWithShipyard(gg_rct_Town_Hall_Dalaran, gg_rct_Town_Hall_Shipyard_Dalaran)
	call AddComputerStartLocationPossibleRaceLast(WOWR_RACE_DALARAN)

    // South
	call AddComputerStartLocationRectWithShipyard(gg_rct_Town_Hall_Sunken_Ruins, gg_rct_Town_Hall_Shipyard_Sunken_Ruins)
	call AddComputerStartLocationPossibleRaceLast(WOWR_RACE_NAGA)
	call AddComputerStartLocationPossibleRaceLast(WOWR_RACE_PANDAREN)

    // Outland
	call AddComputerStartLocationRectWithShipyard(gg_rct_Town_Hall_Outland, gg_rct_Town_Hall_Shipyard_Outland)
	call AddComputerStartLocationPossibleRaceLast(WOWR_RACE_DEMON)
	call AddComputerStartLocationPossibleRaceLast(WOWR_RACE_LOST_ONES)
	call AddComputerStartLocationPossibleRaceLast(WOWR_RACE_FEL_ORC)
	call AddComputerStartLocationPossibleRaceLast(WOWR_RACE_DRAENEI)
	call AddComputerStartLocationPossibleRaceLast(WOWR_RACE_OGRE)
endfunction

endlibrary
